version: "3.9"
services:
  datastore:
    build:
      context: .
      dockerfile: Dockerfile-datastore
    environment:
      - PORT=8484
    ports:
      - 8484:8484
  solr:
    build:
      context: .
      dockerfile: Dockerfile-solr
    ports:
      - 8983:8983
